// <auto-generated />
using System;
using IvaFacilitador.Data.Payroll;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IvaFacilitador.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20251014015219_AddPayrollBase")]
    partial class AddPayrollBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Funcion")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("EmpresaId", "Cedula")
                        .IsUnique();

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.CuentaContable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QboAccountId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("QboAccountName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("EmpresaId", "SectorId", "Tipo")
                        .IsUnique()
                        .HasFilter("[SectorId] IS NOT NULL");

                    b.ToTable("CuentasContables");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RealmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SepararContabilidadPorSectores")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("RealmId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Horas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nota")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<Guid>("PeriodoColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoColaboradorId", "Fecha", "Tipo")
                        .IsUnique();

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Feriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FactorPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Fecha")
                        .IsUnique();

                    b.ToTable("Feriados");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "FechaInicio", "FechaFin");

                    b.ToTable("Periodos");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.PeriodoColaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("PeriodoId", "ColaboradorId")
                        .IsUnique();

                    b.ToTable("PeriodoColaboradores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Sectores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Colaborador", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Empresa", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvaFacilitador.Domain.Payroll.Sector", "Sector")
                        .WithMany("Colaboradores")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.CuentaContable", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Empresa", "Empresa")
                        .WithMany("Cuentas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvaFacilitador.Domain.Payroll.Sector", "Sector")
                        .WithMany("Cuentas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Evento", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.PeriodoColaborador", "PeriodoColaborador")
                        .WithMany("Eventos")
                        .HasForeignKey("PeriodoColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PeriodoColaborador");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Feriado", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Empresa", "Empresa")
                        .WithMany("Feriados")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Periodo", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Empresa", "Empresa")
                        .WithMany("Periodos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.PeriodoColaborador", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Colaborador", "Colaborador")
                        .WithMany("PeriodoColaboradores")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IvaFacilitador.Domain.Payroll.Periodo", "Periodo")
                        .WithMany("PeriodoColaboradores")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Sector", b =>
                {
                    b.HasOne("IvaFacilitador.Domain.Payroll.Empresa", "Empresa")
                        .WithMany("Sectores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Colaborador", b =>
                {
                    b.Navigation("PeriodoColaboradores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Empresa", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Cuentas");

                    b.Navigation("Feriados");

                    b.Navigation("Periodos");

                    b.Navigation("Sectores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Periodo", b =>
                {
                    b.Navigation("PeriodoColaboradores");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.PeriodoColaborador", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("IvaFacilitador.Domain.Payroll.Sector", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Cuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
